# Generated by Django 2.2.5 on 2021-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
