# Generated by Django 2.2.5 on 2021-02-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_kakao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='bank_account',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
