# Generated by Django 2.2.5 on 2021-02-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210208_1837'),
        ('users', '0004_auto_20210208_1601'),
    ]

    operations = [
    ]
