# Generated by Django 2.2.5 on 2021-02-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20210209_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
