# Generated by Django 2.2.5 on 2021-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_location_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
