# Generated by Django 2.2.5 on 2021-02-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40, null=True)),
                ('content', models.TextField(blank=True)),
                ('receiver', models.ForeignKey(default='receiver', on_delete=django.db.models.deletion.CASCADE, related_name='alarm_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default='sender', on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
