# Generated by Django 2.2.5 on 2021-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
