# Generated by Django 2.2.5 on 2021-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='ischeck',
            field=models.BooleanField(default=False),
        ),
    ]
