# Generated by Django 2.2.5 on 2021-02-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alarm_ischeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
