# Generated by Django 2.2.5 on 2021-02-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alarm_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='isFirst',
            field=models.BooleanField(default=False),
        ),
    ]
