# Generated by Django 2.2.5 on 2021-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210218_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link_address',
            field=models.URLField(blank=True),
        ),
    ]
