# Generated by Django 2.2.5 on 2021-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210222_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('진행 중', '진행 중'), ('모집 완료', '모집 완료'), ('기간 만료', '기간 만료')], default='진행 중', max_length=16),
        ),
    ]
