# Generated by Django 2.2.5 on 2021-02-08 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0005_immaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='participants',
            field=models.ManyToManyField(related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
