# Generated by Django 2.2.5 on 2021-02-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchase_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='link_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='explain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='max_people',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='room_photos')),
                ('purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='purchases.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
