# Generated by Django 2.2.5 on 2021-02-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_auto_20210208_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='room_photos'),
        ),
    ]
