# Generated by Django 2.2.5 on 2021-02-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
