# Generated by Django 2.2.5 on 2021-02-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchase_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
