# Generated by Django 2.2.5 on 2021-02-15 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_auto_20210215_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='immaterial',
            name='category',
            field=models.CharField(choices=[('인터넷 서비스 공유', '인터넷 서비스 공유'), ('교육', '교육'), ('여가 활동', '여가 활동'), ('기타', '기타')], default='인터넷 서비스 공유', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('음식', '음식'), ('생필품', '생필품'), ('기타', '기타')], default='음식', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
    ]
