# Generated by Django 2.2.5 on 2021-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField()),
                ('rate', models.IntegerField()),
                ('purchases', models.ManyToManyField(blank=True, to='purchases.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
